### ISSUE TITLE
Under the "Porn" section, there is a site called "PedoChan" containing child porn!

### ISSUE THREAD

**Issue by Ornataweaver** [HelloZeroNet/ZeroSites#7]
Take it off immediately.
Who the fuck allowed it there in the first place?
Is there no approval mechanism to deny this type of shit on ZeroSites?

**Comment by HelloZeroNet** [comment]
Thanks for the info, I have removed the link, there is no pre-approval for the site submission currently.

**Comment by Ornataweaver** [comment]
I suggest there would be, this is a matter of reputation.
Also remember your childhood, don't let there be child abuse under your control. If you have ever been angry with politicians in your life, now you are in power here. How would you choose makes history.
